/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminalcontroldemo;

/**
 *
 * @author Administrator
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabpanel = new javax.swing.JTabbedPane();
        settings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        videoSettings = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mainVideoPrePAL = new javax.swing.JComboBox<>();
        assVideoPrePAL = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        mainVideoPAL = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        assVideoPAL = new javax.swing.JComboBox<>();
        videoPALApply = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        mainVidSource = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        assVideoSource = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        selectVidInput = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        selectVidOutput = new javax.swing.JComboBox<>();
        VidSourceApply = new javax.swing.JButton();
        selectVidApply = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        VGAOutput = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        HDMI2Output = new javax.swing.JComboBox<>();
        HDMI3Output = new javax.swing.JComboBox<>();
        VdiMatrixApply = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        function = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jLabel1.setText("视频设置");

        jLabel2.setText("音频设置");

        jLabel3.setText("主视频优选分辨率");

        jLabel4.setText("辅视频优选分辨率");

        mainVideoPrePAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "1080P(1920x1080)", "720P(1280x720)", "W4CIF(1024x576)", "4CIF(704x576)", "WCIF(512x288)", "CIF(352x288)" }));
        mainVideoPrePAL.setMinimumSize(new java.awt.Dimension(128, 21));
        mainVideoPrePAL.setPreferredSize(new java.awt.Dimension(128, 21));
        mainVideoPrePAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainVideoPrePALActionPerformed(evt);
            }
        });

        assVideoPrePAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "1080P(1920x1080)", "720P(1280x720)", "WSXGA+(1680x1050)", "UXGA(1600x1200)", "WSXGA(1440x900)", "WXGA(1366x768)", "SXGA(1280x1024)", "WXGA(1280x800)", "WXGA(1280x768)", "XGA(1024*768)" }));

        jLabel5.setText("主视频输出分辨率");

        mainVideoPAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1080P_60fps", "1080P_24fps", "1080P_25fps", "1080P_29.97fps", "1080P_30fps", "1080P_50fps", "1080P_59.94fps", "UXGA(1600×1200)_60Hz", "WSXGA+(1680×1050)_60Hz", "SXGA(1280×1024)_60Hz", "WSXGA(1440×900)_60Hz", "720P_50fps", "720P_60fps", "XGA(1024×768)_60Hz", "XGA(1024×768)_75Hz", "WXGA(1366×768)_60Hz", "WXGA(1280×800)_60Hz" }));

        jLabel6.setText("辅视频输出分辨率");

        assVideoPAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "1080P_60fps", "1080P_24fps", "1080P_25fps", "1080P_29.97fps", "1080P_30fps", "1080P_50fps", "1080P_59.94fps", "UXGA(1600×1200)_60Hz", "WSXGA+(1680×1050)_60Hz", "SXGA(1280×1024)_60Hz", "WSXGA(1440×900)_60Hz", "720P_50fps", "720P_60fps", "XGA(1024×768)_60Hz", "XGA(1024×768)_75Hz", "WXGA(1366×768)_60Hz", "WXGA(1280×800)_60Hz" }));

        videoPALApply.setText("应用");

        jLabel7.setText("主视频源");

        mainVidSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "内置摄像机" }));
        mainVidSource.setMinimumSize(new java.awt.Dimension(128, 21));
        mainVidSource.setPreferredSize(new java.awt.Dimension(128, 21));

        jLabel8.setText("辅视频源");

        assVideoSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VGA/YPbPr_1", "HDMI_1" }));
        assVideoSource.setMinimumSize(new java.awt.Dimension(128, 21));
        assVideoSource.setPreferredSize(new java.awt.Dimension(128, 21));

        jLabel9.setText("输入:VGA/YpbPr_1");

        selectVidInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VGA", "YPbPr_1" }));
        selectVidInput.setMinimumSize(new java.awt.Dimension(128, 21));
        selectVidInput.setPreferredSize(new java.awt.Dimension(128, 21));

        jLabel10.setText("输出:VGA/YpbPr_1");

        selectVidOutput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VGA", "YPbPr_1" }));
        selectVidOutput.setMinimumSize(new java.awt.Dimension(128, 21));
        selectVidOutput.setPreferredSize(new java.awt.Dimension(128, 21));

        VidSourceApply.setText("应用");

        selectVidApply.setText("应用");

        VGAOutput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "无输出", "主视频", "辅视频", "VGA/YPbPr_1", "内置摄像机" }));
        VGAOutput.setAutoscrolls(true);
        VGAOutput.setMinimumSize(new java.awt.Dimension(128, 21));
        VGAOutput.setPreferredSize(new java.awt.Dimension(128, 21));

        jLabel11.setText("VGA/YpbPr_1");

        jLabel12.setText("HDMI_2");

        jLabel13.setText("HDMI_3");

        HDMI2Output.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "主视频", "辅视频", "VGA/YPbPr_1", "内置摄像机" }));
        HDMI2Output.setMinimumSize(new java.awt.Dimension(128, 21));
        HDMI2Output.setPreferredSize(new java.awt.Dimension(128, 21));

        HDMI3Output.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "主视频", "辅视频", "VGA/YPbPr_1", "内置摄像机" }));
        HDMI3Output.setMinimumSize(new java.awt.Dimension(128, 21));
        HDMI3Output.setPreferredSize(new java.awt.Dimension(128, 21));

        VdiMatrixApply.setText("应用");

        javax.swing.GroupLayout videoSettingsLayout = new javax.swing.GroupLayout(videoSettings);
        videoSettings.setLayout(videoSettingsLayout);
        videoSettingsLayout.setHorizontalGroup(
            videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoSettingsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videoSettingsLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(selectVidOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222)
                        .addComponent(selectVidApply))
                    .addGroup(videoSettingsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(selectVidInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(videoSettingsLayout.createSequentialGroup()
                        .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainVideoPrePAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assVideoPrePAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(videoSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(mainVideoPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(videoSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(assVideoPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(videoPALApply))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(videoSettingsLayout.createSequentialGroup()
                        .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(68, 68, 68)
                        .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(videoSettingsLayout.createSequentialGroup()
                                .addComponent(assVideoSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(221, 221, 221)
                                .addComponent(VidSourceApply))
                            .addComponent(mainVidSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(videoSettingsLayout.createSequentialGroup()
                        .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(videoSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HDMI3Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(videoSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HDMI2Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, videoSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(48, 48, 48)
                                .addComponent(VGAOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(228, 228, 228)
                        .addComponent(VdiMatrixApply)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        videoSettingsLayout.setVerticalGroup(
            videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mainVideoPrePAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(mainVideoPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(assVideoPrePAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(assVideoPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoPALApply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mainVidSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(assVideoSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VidSourceApply)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(selectVidInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(selectVidOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectVidApply))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(VGAOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(HDMI2Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(videoSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(HDMI3Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VdiMatrixApply))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(settingsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(settingsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(videoSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(videoSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        mainTabpanel.addTab("设置", settings);

        javax.swing.GroupLayout functionLayout = new javax.swing.GroupLayout(function);
        function.setLayout(functionLayout);
        functionLayout.setHorizontalGroup(
            functionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1314, Short.MAX_VALUE)
        );
        functionLayout.setVerticalGroup(
            functionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        mainTabpanel.addTab("功能", function);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabpanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabpanel)
                .addContainerGap())
        );

        mainTabpanel.getAccessibleContext().setAccessibleName("tab2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainVideoPrePALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainVideoPrePALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainVideoPrePALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HDMI2Output;
    private javax.swing.JComboBox<String> HDMI3Output;
    private javax.swing.JComboBox<String> VGAOutput;
    private javax.swing.JButton VdiMatrixApply;
    private javax.swing.JButton VidSourceApply;
    private javax.swing.JComboBox<String> assVideoPAL;
    private javax.swing.JComboBox<String> assVideoPrePAL;
    private javax.swing.JComboBox<String> assVideoSource;
    private javax.swing.JPanel function;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane mainTabpanel;
    private javax.swing.JComboBox<String> mainVidSource;
    private javax.swing.JComboBox<String> mainVideoPAL;
    private javax.swing.JComboBox<String> mainVideoPrePAL;
    private javax.swing.JButton selectVidApply;
    private javax.swing.JComboBox<String> selectVidInput;
    private javax.swing.JComboBox<String> selectVidOutput;
    private javax.swing.JPanel settings;
    private javax.swing.JButton videoPALApply;
    private javax.swing.JPanel videoSettings;
    // End of variables declaration//GEN-END:variables
}
